In [16]:
## 문제 1. 암호해독 << En-coding 문제 >>


str1 = '   + -- + - + -   '.replace('+', '1').replace('-', '0').replace(' ', '')
str2 ='   + --- + - +   '.replace('+', '1').replace('-', '0').replace(' ', '')
str3 = '   + -- + - + -   '.replace('+', '1').replace('-', '0').replace(' ', '')
str4 = '   + - + - + - +   '.replace('+', '1').replace('-', '0').replace(' ', '')


# 2진수 -> 10진수 변환
print(int(str1, 2))
print(int(str2, 2))
print(int(str3, 2))
print(int(str4, 2))

74
69
74
85


In [18]:
print(str1)
print(str2)
print(str3)
print(str4)

1001010
1000101
1001010
1010101


In [21]:
print(chr(74)+
chr(69)+
chr(74)+
chr(85))

JEJU


In [ ]:
## 문제 2. JAVA독과 함께!


첫 문제를 푼 라이캣은 자신의 한계가 어디인지 궁금했어요. 그렇지만 높은 곳은 혼자 갈 수 없죠. 그래서 동료를 모으기로 결심했습니다.

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/8e1910a3-5029-4116-9f46-a43960cf6b98/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/8e1910a3-5029-4116-9f46-a43960cf6b98/Untitled.png)

하지만 선뜻 멀고 험한길을 듣보잡 라이캣과 함께 해줄 친구들은 없었답니다.

라이캣은 랩처럼 대사를 외우고 다녔어요.

> 내 동료가 되어라냥!

- 뭐지? 명령문인가?
- '냥'이라니, 자연어처리가 힘들겠는걸?
- 동료는 sum인가, concat인가? axis 0인가, 1인가?

동물 친구들은 수근거렸습니다. 혼자 코딩하기 좋아하는 동물 친구들은 동료라는 말도 이해하지 못했어요.

---

그러던 중 동물 친구들 중에서 가장 재빠르고, 영리한 JAVA독이 말했습니다. ~~사실 자바독은 늘 Python을 해보고 싶었거든요.~~ 그래서 라이캣이 파이와 썬의 보물을 찾으러 가는 도구로 `파이썬`을 사용한다고 하였을 때 눈여겨 보고 있었어요.

> 내가 동료되길 원해? 그렇다면 검증필!?

라이캣은 거절할 이유가 없었죠.

> 좋아냥!

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/8bfc8bfc-5e59-4423-ad9f-3fb5e126e773/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/8bfc8bfc-5e59-4423-ad9f-3fb5e126e773/Untitled.png)

---

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a8ccb0fd-a673-4fda-b537-70349cde99ea/.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a8ccb0fd-a673-4fda-b537-70349cde99ea/.png)

저기 징검다리가 보이지? 내 친구들이 징검다리를 건널거야! 하지만 징검다리는 버틸수 있는 내구도가 한계가 있지! 내 친구들의 **몸무게**, **돌의 내구도**, **친구들의 점프력**을 고려하여 내 친구 루비독, 피치피독, 씨-독, 코볼독이 각각 다리를 건널 수 있는지 알아봐줘! 친구들은 더 추가 될 수도, 덜 건널 수도 있어!

1. 각 돌들이 얼마나 버틸수 있는지 배열로 주어집니다. (내구도 0까지는 독의 몸무게를 버틸 수 있습니다. 0미만이 되면 독은 살아남지 못합니다.)

2. 각 독들의 개인정보가 JSON(JSON은 큰 따옴표로 묶여야 합니다. **가능하다면 json을 import하여 풀어보세요!**)으로 주어집니다. 개인정보는 보호되지 않습니다.

3. 각 돌에 독들이 착지할 때 돌의 내구도는 몸무게만큼 줄어듭니다.
    ex) [1,2,1,4] 각 돌마다 몸무게 1인 독 1마리 2마리 1마리 4마리의 착지를 버틸 수 있습니다.

4. 독들의 점프력이 각자 다릅니다. 
    ex) 점프력이 2라면 2칸씩 점프하여 착지합니다.

4. 각 독들은 순서대로만 다리를 건넙니다.

```python
**입력**
돌의내구도 = [1, 2, 1, 4]
독 = [{
    "이름" : "루비독",
    "나이" : "95년생",
    "점프력" : "3",
    "몸무게" : "4",
    },{
    "이름" : "피치독",
    "나이" : "95년생",
    "점프력" : "3",
    "몸무게" : "3",
    },{
    "이름" : "씨-독",
    "나이" : "72년생",
    "점프력" : "2",
    "몸무게" : "1",
    },{
    "이름" : "코볼독",
    "나이" : "59년생",
    "점프력" : "1",
    "몸무게" : "1",
    },
]

**출력**
생존자 : ['씨-독']

**입력**
돌의내구도 = [5, 3, 4, 1, 3, 8, 3]
독 = [{
    "이름" : "루비독",
    "나이" : "95년생",
    "점프력" : "3",
    "몸무게" : "4",
    },{
    "이름" : "피치독",
    "나이" : "95년생",
    "점프력" : "3",
    "몸무게" : "3",
    },{
    "이름" : "씨-독",
    "나이" : "72년생",
    "점프력" : "2",
    "몸무게" : "1",
    },{
    "이름" : "코볼독",
    "나이" : "59년생",
    "점프력" : "1",
    "몸무게" : "1",
    },
]

**출력**
생존자 : ['루비독', '씨-독']
```

In [25]:
# 예제 1

돌의내구도 = [1, 2, 1, 4]
독 = [{
    "이름" : "루비독",
    "나이" : "95년생",
    "점프력" : "3",
    "몸무게" : "4",
    },{
    "이름" : "피치독",
    "나이" : "95년생",
    "점프력" : "3",
    "몸무게" : "3",
    },{
    "이름" : "씨-독",
    "나이" : "72년생",
    "점프력" : "2",
    "몸무게" : "1",
    },{
    "이름" : "코볼독",
    "나이" : "59년생",
    "점프력" : "1",
    "몸무게" : "1",
    },
]

In [23]:
def 징검다리를건너라(돌의내구도, 독):
    answer = [독[i]['이름']for i in range(len(독))]
    
    return answer

print(징검다리를건너라(돌의내구도, 독))

['루비독', '피치독', '씨-독', '코볼독']


In [24]:
def 징검다리를건너라(돌의내구도, 독):
    answer = [elem['이름'] for elem in 독]
    
    return answer

print(징검다리를건너라(돌의내구도, 독))

['루비독', '피치독', '씨-독', '코볼독']


In [30]:
def 징검다리를건너라(돌의내구도, 독):
    answer = [elem['이름'] for elem in 독]
    
    for elem in 독:
        독의위치 = 0
        while 독의위치 < len(돌의내구도)-1:
            독의위치 += int(elem['점프력'])
            돌의내구도[독의위치-1] -= int(elem['몸무게'])
            
            if 돌의내구도[독의위치-1] < 0:
                answer[answer.index(elem['이름'])] = 'fail'
                break
    return [i for i in answer if i != 'fail']
    

print(징검다리를건너라(돌의내구도.copy(), 독.copy())) # copy() 안해주면 내부에서 값이 바뀜

['씨-독']


In [34]:
ll = [1, 2, 3, 4, 5]

def change(l):
    l[0] = 1000
    
change(ll)

ll # 리스트는 주소를 전달해주기 때문에, 안에서 값이 수정됨

[1000, 2, 3, 4, 5]

In [37]:
xx = 100

def change(x):
    x += 1000
    
change(xx)

xx # 원래 전역 변수는 값이 바뀌지 않으나(함수는 주소값은 그대로 있고 값만 복사됨)

100

In [38]:
# remove : 0(N)
# del : O(1) => 따라서 del을 사용하자 !



def 징검다리를건너라(돌의내구도, 독):
    answer = [elem['이름'] for elem in 독]
    
    for elem in 독:
        독의위치 = 0
        while 독의위치 < len(돌의내구도)-1:
            독의위치 += int(elem['점프력'])
            돌의내구도[독의위치-1] -= int(elem['몸무게'])
            
            if 돌의내구도[독의위치-1] < 0:
                del answer[answer.index(elem['이름'])]
                break
    return answer
    

print(징검다리를건너라(돌의내구도.copy(), 독.copy())) # copy() 안해주면 내부에서 값이 바뀜

['씨-독']


In [39]:
# json 처리 방식

import json

JSON독 = json.dumps(독, ensure_ascii=False)
JSON독[0]
JSON독[:10] # str 타입 !

'[{"이름": "루'

In [40]:
JSON독 = json.loads(JSON독)
JSON독[0] # list 타입으로 잘 로드됨 !

{'이름': '루비독', '나이': '95년생', '점프력': '3', '몸무게': '4'}

In [ ]:
## 문제 3. 섬으로 건너가라!

입력
대기인원 = 14000605

출력
2025년 ㅠㅠ2월 413일 11시 0분 출발

입력
대기인원 = 1200202

출력
2020년 1월 1000일 11시 0분 출발

In [56]:
# 정답
import datetime

오늘시간 = datetime.datetime.today()
대기인원 = 14000605


def solution(대기인원):
    일년일수 = 0
    for i in range(10, 0, -1):
        일년일수 += 2**i
        
    
    년 = (대기인원 // 1200) // 일년일수
    남은일수 = (대기인원 // 1200) % 일년일수 # 대기일 : (대기인원 // 1200)
    
    월별일수누적값 = 0
    월 = 0
    for i in range(10, 0, -1):
        차감일 = 월별일수누적값
        월별일수누적값 += 2**i
        월 += 1
        
        if 월별일수누적값 > 남은일수:
            break
            
            
    일 = 남은일수 - 차감일
    최종남은인원 = 대기인원 % 1200
    시 = 최종남은인원 // 100+9
    
    
    출발분 = [25, 50, 75, 85, 100]
    해당시간에남은인원 = 최종남은인원 % 100
    
    for i in 출발분:
        if i > 해당시간에남은인원:
            분 = 출발분.index(i) * 10
            break
            
            
    if 최종남은인원 % 100 == 9:
        시 += 1
        분 = 0
    
    if(오늘시간.minute + 분 > 60):
        분 = (오늘시간.minute + 분) - 60
        시 += 1
    
    
    #print(년, 월, 일, 시, 분)
    return f'{년+2020}년 {월}월 {일}일 {시}시 {분}분 출발'
    
solution(대기인원)

'2025년 2월 413일 11시 0분 출발'

In [58]:
# 문제4. 자리를 양보해가며!

graph = {100: set([67, 66]),
         67: set([100, 82, 63]),
         66: set([100, 73, 69]),
         82: set([67, 61, 79]),
         63: set([67]),
         73: set([66]),
         69: set([66, 65, 81]),
         61: set([82]),
         79: set([82, 87, 77]),
         65: set([69, 84, 99]),
         81: set([69]),
         87: set([79, 31, 78]),
         77: set([79]),
         84: set([65]),
         99: set([65]),
         31: set([87]),
         78: set([87])}

In [ ]:
graph = {100: new Set([67, 66]),
         67: new Set([100, 82, 63]),
         66: new Set([100, 73, 69]),
         82: new Set([67, 61, 79]),
         63: new Set([67]),
         73: new Set([66]),
         69: new Set([66, 65, 81]),
         61: new Set([82]),
         79: new Set([82, 87, 77]),
         65: new Set([69, 84, 99]),
         81: new Set([69]),
         87: new Set([79, 31, 78]),
         77: new Set([79]),
         84: new Set([65]),
         99: new Set([65]),
         31: new Set([87]),
         78: new Set([87])};

In [61]:
def 깊이우선탐색(graph, start): # 스택 !
    방문 = []
    stack = [start] # 시작노드 처음 담기
    
    while stack: # 스택에 값이 없을 때까지 진행
        n = stack.pop()
        if n not in 방문:
            방문.append(n)
            차집합 = graph[n] - set(방문)
            stack += 차집합 # 스택에 누적
            
            print(f'visited : {방문}')
            print(f'stack : {stack}')
            
    return 방문

깊이우선탐색(graph, 100)
    

visited : [100]
stack : [66, 67]
visited : [100, 67]
stack : [66, 82, 63]
visited : [100, 67, 63]
stack : [66, 82]
visited : [100, 67, 63, 82]
stack : [66, 61, 79]
visited : [100, 67, 63, 82, 79]
stack : [66, 61, 77, 87]
visited : [100, 67, 63, 82, 79, 87]
stack : [66, 61, 77, 78, 31]
visited : [100, 67, 63, 82, 79, 87, 31]
stack : [66, 61, 77, 78]
visited : [100, 67, 63, 82, 79, 87, 31, 78]
stack : [66, 61, 77]
visited : [100, 67, 63, 82, 79, 87, 31, 78, 77]
stack : [66, 61]
visited : [100, 67, 63, 82, 79, 87, 31, 78, 77, 61]
stack : [66]
visited : [100, 67, 63, 82, 79, 87, 31, 78, 77, 61, 66]
stack : [73, 69]
visited : [100, 67, 63, 82, 79, 87, 31, 78, 77, 61, 66, 69]
stack : [73, 65, 81]
visited : [100, 67, 63, 82, 79, 87, 31, 78, 77, 61, 66, 69, 81]
stack : [73, 65]
visited : [100, 67, 63, 82, 79, 87, 31, 78, 77, 61, 66, 69, 81, 65]
stack : [73, 99, 84]
visited : [100, 67, 63, 82, 79, 87, 31, 78, 77, 61, 66, 69, 81, 65, 84]
stack : [73, 99]
visited : [100, 67, 63, 82, 79, 87, 31, 7

[100, 67, 63, 82, 79, 87, 31, 78, 77, 61, 66, 69, 81, 65, 84, 99, 73]

In [73]:
def 깊이우선탐색(graph, start): # 스택 !
    방문 = []
    stack = [start] # 시작노드 처음 담기
    
    while stack: # 스택에 값이 없을 때까지 진행
        n = stack.pop()
        if n not in 방문:
            방문.append(n)
            차집합 = graph[n] - set(방문)
            
            if len(차집합) == 0: # 깊이 끝으로 다 이동하였다면,
                방문 += stack
                break
                
            stack.append(min(차집합)) # 작은값(or 큰값)만 출력    
            
            print(f'visited : {방문}')
            print(f'stack : {stack}')
            
    return 방문

깊이우선탐색(graph, 100)
    

visited : [100]
stack : [66]
visited : [100, 66]
stack : [69]
visited : [100, 66, 69]
stack : [65]
visited : [100, 66, 69, 65]
stack : [84]


[100, 66, 69, 65, 84]

In [ ]:
# 큰값: [100, 67, 82, 79, 87, 78]
# 작은값: [100, 66, 69, 65, 84]

In [75]:
# 아스키코드로 변환 !
''.join(chr(i) for i in [67, 82, 79, 87, 78]) # max

'CROWN'

In [74]:
''.join(chr(i) for i in [66, 69, 65, 84])

'BEAT'

# 기본 알고리즘 강좌

In [81]:
%%time ### O(n)
## 1부터 100까지의 합


x = 0
n = 100

for i in range(1, n+1):
    x += i
    
print(x)

5050
CPU times: user 383 µs, sys: 135 µs, total: 518 µs
Wall time: 1.2 ms


In [80]:
%%time ### O(1)
# 시그마 공식 : n*(n+1)//2


x = 0
n = 100

x = n*(n+1)//2
    
print(x)

5050
CPU times: user 98 µs, sys: 9 µs, total: 107 µs
Wall time: 112 µs


In [78]:
## 1부터 100까지의 곱

# 팩토리얼 (!)


x = 1
n = 5

for i in range(1, n+1):
    x *= i
    
print(x)

120


In [82]:
## 1부터 100까지의 합 (재귀)

def f(n):
    if n <= 1:
        return 1
    else:
        return n + f(n-1)
    

n = 100    
print(f(n))

5050


In [84]:
## 1부터 100까지의 곱 (재귀)

def f(n):
    if n <= 1:
        return 1
    else:
        return n * f(n-1)
    

n = 5   
print(f(n))

120


In [85]:
###
while True:
    if input('##') == 'exit':
        break
    if input('##') == 'hi':
        print('hello world')
    else:
        continue

##exit


In [87]:
# 무한루프 -재귀함수

def console():
    if input('##') == 'exit':
        return None
    if input('##') == 'hi':
        print('hello world')
    console()
console()

##wefw
##wefwef
##wefwefsd
##exit
##exit


In [88]:
# 2진수, 8진수 16진수 구하기
print(bin(11))
print(oct(11))
print(hex(11))

0b1011
0o13
0xb


In [89]:
print(bin(11)[2:])
print(oct(11)[2:])
print(hex(11)[2:])

1011
13
b


In [ ]:
## 2진수 구하기 - 반복문

In [1]:
## 문제 6. 밭의 비밀

import numpy as np

첫번째밭 = [
    [1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1]
]

두번째밭 = [
    [0, 0, 0, 0, 1],
    [0, 0, 0, 0, 3],
    [0, 0, 0, 0, 4],
    [0, 2, 0, 0, 2],
    [4, 5, 0, 2, 0]
]

In [2]:
np.rot90(첫번째밭, 1) # 반시계 회전

array([[0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [3]:
np.rot90(첫번째밭, -1) # 시계 회전

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0]])

In [4]:
# 1
np.rot90(두번째밭, 1) + np.array(첫번째밭)

array([[2, 3, 4, 2, 0],
       [0, 0, 1, 0, 3],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 2, 6],
       [0, 0, 1, 0, 5]])

In [6]:
# 2
np.array(첫번째밭) - np.rot90(두번째밭, 1)

array([[ 0, -3, -4, -2,  0],
       [ 0,  0,  1,  0, -1],
       [ 0,  0,  1,  0,  1],
       [ 0,  0,  1, -2, -4],
       [ 0,  0,  1,  0, -3]])

In [7]:
# 3
np.array(첫번째밭) * np.rot90(두번째밭, 1)

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 4]])

In [8]:
# 4 <<행렬의 곱>> => @
np.array(첫번째밭) @ np.rot90(두번째밭, 1)

array([[1, 3, 4, 2, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 4]])

In [9]:
정답 = np.rot90(두번째밭, 1) + np.array(첫번째밭)
''.join([str(i) for i in 정답[0]])

'23420'

In [10]:
# 8진수 => 10진수 변환 : int()

int(''.join([str(i) for i in 정답[0]]), 8)

10000

In [12]:
chr(int(''.join([str(i) for i in 정답[1]]), 8))

'C'

In [13]:
# 전체 정답 : 만장굴
for k in range(5):
    print(chr(int(''.join([str(i) for i in 정답[k]]), 8)))

✐
C
A
V
E
